$ErrorActionPreference = "Stop"
$raw = Join-Path $PSScriptRoot "words-raw.txt"
$outDir = Join-Path $PSScriptRoot "..\src\data"
$outFile = Join-Path $outDir "words.json"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$lines = Get-Content $raw -Encoding UTF8 | ForEach-Object { $_.Trim() } | Where-Object { $_ -and $_ -notmatch '^#' }
# базовые переводы (фрагмент; остальные — шаблон)
$ru = @{
  "the"="определённый артикль the"; "of"="родительный: из, о"; "to"="к, чтобы; инфинитив"
  "and"="и"; "a"="неопределённый артикль"; "in"="в, внутри"; "is"="есть, является"
  "it"="это, оно"; "you"="ты, вы"; "that"="тот, что"; "he"="он"; "was"="был(а)"
  "for"="для, в течение"; "on"="на"; "are"="есть (мн.ч.)"; "with"="с, вместе с"
  "as"="как, в качестве"; "I"="я"; "his"="его"; "they"="они"; "be"="быть"
  "at"="в, у (точка)"; "one"="один"; "have"="иметь"; "this"="этот"; "from"="из, от"
  "or"="или"; "had"="имел"; "by"="у, к, посредством"; "word"="слово"; "but"="но"
  "what"="что"; "some"="некоторые"; "we"="мы"; "can"="мочь"; "out"="наружу"
  "other"="другой"; "were"="были"; "all"="всё, все"; "there"="там"; "when"="когда"
  "up"="вверх"; "use"="использовать"; "your"="твой"; "how"="как"; "said"="сказал"
  "an"="неопределённый артикль"; "each"="каждый"; "she"="она"; "which"="который"
  "do"="делать"; "their"="их"; "time"="время"; "if"="если"; "will"="будет (буд.)"
  "way"="путь, способ"; "about"="о, примерно"; "many"="много"; "then"="тогда"
  "them"="их, им"; "write"="писать"; "would"="бы (условн.)"; "like"="нравиться, как"
  "so"="так, поэтому"; "these"="эти"; "her"="её"; "long"="длинный"; "make"="делать"
  "thing"="вещь"; "see"="видеть"; "him"="его, ему"; "two"="два"; "has"="имеет"
  "look"="смотреть"; "more"="больше"; "day"="день"; "could"="мог бы"; "go"="идти"
  "come"="приходить"; "did"="сделал"; "number"="число"; "sound"="звук"; "no"="нет"
  "most"="большинство"; "people"="люди"; "my"="мой"; "over"="над, через"
  "know"="знать"; "water"="вода"; "than"="чем"; "call"="звонить, называть"
  "first"="первый"; "who"="кто"; "may"="мочь"; "down"="вниз"; "side"="сторона"
  "been"="был (прич.)"; "now"="сейчас"; "find"="находить"; "any"="любой"
  "new"="новый"; "work"="работа"; "part"="часть"; "take"="брать"; "get"="получать"
  "place"="место"; "made"="сделанный"; "live"="жить"; "where"="где"; "after"="после"
  "back"="назад"; "little"="маленький"; "only"="только"; "round"="круглый"
  "man"="мужчина"; "year"="год"; "came"="пришёл"; "show"="показывать"
  "every"="каждый"; "good"="хороший"; "me"="меня"; "give"="давать"; "our"="наш"
  "under"="под"; "name"="имя"; "very"="очень"; "through"="через"; "just"="только что"
  "form"="форма"; "sentence"="предложение"; "great"="великий"; "think"="думать"
  "say"="сказать"; "help"="помощь"; "low"="низкий"; "line"="линия"; "much"="много"
  "mean"="означать"; "before"="до"; "move"="двигать"; "right"="правый, верно"
  "boy"="мальчик"; "old"="старый"; "too"="тоже, слишком"; "same"="тот же"
  "tell"="говорить"; "does"="делает"; "set"="набор"; "three"="три"; "want"="хотеть"
  "air"="воздух"; "well"="хорошо"; "also"="также"; "play"="играть"; "small"="малый"
  "end"="конец"; "put"="класть"; "home"="дом"; "read"="читать"; "hand"="рука"
  "large"="большой"; "spell"="произносить по буквам"; "add"="добавлять"
  "even"="даже"; "land"="земля"; "here"="здесь"; "must"="должен"; "big"="большой"
  "high"="высокий"; "such"="такой"; "follow"="следовать"; "act"="действовать"
  "why"="почему"; "ask"="спрашивать"; "change"="менять"; "went"="пошёл"
  "light"="свет"; "kind"="вид, добрый"; "off"="выкл."; "need"="нуждаться"
  "house"="дом"; "picture"="картина"; "try"="пробовать"; "us"="нас"
  "again"="снова"; "animal"="животное"; "point"="точка"; "mother"="мать"
  "world"="мир"; "near"="рядом"; "build"="строить"; "earth"="земля"
  "father"="отец"; "head"="голова"; "stand"="стоять"; "own"="свой"
  "page"="страница"; "should"="следует"; "country"="страна"; "found"="нашёл"
  "answer"="ответ"; "school"="школа"; "grow"="расти"; "study"="учиться"
  "still"="всё ещё"; "learn"="учить"; "plant"="растение"; "food"="еда"
  "sun"="солнце"; "four"="четыре"; "between"="между"; "state"="штат, состояние"
  "keep"="держать"; "eye"="глаз"; "never"="никогда"; "last"="последний"
  "let"="позволять"; "thought"="мысль"; "city"="город"; "tree"="дерево"
  "farm"="ферма"; "hard"="твёрдый, трудно"; "start"="начинать"; "might"="мог бы"
  "story"="история"; "saw"="увидел"; "far"="далеко"; "sea"="море"; "run"="бежать"
  "while"="пока"; "close"="близко"; "night"="ночь"; "real"="настоящий"
  "life"="жизнь"; "few"="немногие"; "north"="север"; "open"="открытый"
  "together"="вместе"; "next"="следующий"; "white"="белый"; "children"="дети"
  "begin"="начинать"; "got"="получил"; "walk"="идти"; "example"="пример"
  "paper"="бумага"; "group"="группа"; "always"="всегда"; "music"="музыка"
  "both"="оба"; "book"="книга"; "room"="комната"; "friend"="друг"
  "idea"="идея"; "fish"="рыба"; "stop"="остановиться"; "once"="однажды"
  "hear"="слышать"; "cut"="резать"; "sure"="уверенный"; "watch"="смотреть"
  "color"="цвет"; "face"="лицо"; "girl"="девочка"; "young"="молодой"
  "list"="список"; "talk"="говорить"; "bird"="птица"; "soon"="скоро"
  "body"="тело"; "dog"="собака"; "family"="семья"; "leave"="уходить"
  "song"="песня"; "door"="дверь"; "black"="чёрный"; "short"="короткий"
  "wind"="ветер"; "question"="вопрос"; "ship"="корабль"; "area"="область"
  "rock"="камень"; "order"="порядок"; "fire"="огонь"; "south"="юг"
  "problem"="проблема"; "piece"="кусок"; "knew"="знал"; "top"="верх"
  "king"="король"; "space"="пространство"; "best"="лучший"; "hour"="час"
  "true"="истинный"; "hundred"="сто"; "five"="пять"; "remember"="помнить"
  "fast"="быстрый"; "sing"="петь"; "listen"="слушать"; "table"="стол"
  "travel"="путешествовать"; "morning"="утро"; "love"="любовь"; "money"="деньги"
  "road"="дорога"; "map"="карта"; "cold"="холод"; "voice"="голос"; "town"="городок"
  "wait"="ждать"; "plan"="план"; "star"="звезда"; "field"="поле"; "done"="готово"
  "drive"="водить"; "week"="неделя"; "green"="зелёный"; "free"="свободный"
  "minute"="минута"; "strong"="сильный"; "blue"="синий"; "moon"="луна"
  "foot"="ступня"; "system"="система"; "boat"="лодка"; "plane"="самолёт"
  "hot"="горячий"; "bring"="приносить"; "yes"="да"; "heart"="сердце"
  "heavy"="тяжёлый"; "speak"="говорить"; "ice"="лёд"; "sleep"="спать"
  "wall"="стена"; "sky"="небо"; "winter"="зима"; "summer"="лето"
  "happy"="счастливый"; "hope"="надеяться"; "baby"="малыш"; "buy"="покупать"
  "cat"="кошка"; "law"="закон"; "death"="смерть"; "thank"="благодарить"
  "apple"="яблоко"; "dream"="мечта"; "dad"="папа"; "bread"="хлеб"
}
$id = 1
$arr = foreach ($w in $lines) {
  $tr = $ru[$w]
  if (-not $tr) { $tr = "частое слово: $w" }
  [PSCustomObject]@{
    id = $id
    word = $w
    translation = $tr
    example = "Example: This is the word ""$w"" in a sentence."
  }
  $id++
}
$arr | ConvertTo-Json -Depth 5 -Compress | Set-Content $outFile -Encoding UTF8
Write-Host "Wrote $($arr.Count) words to $outFile"
